export const SUDUKO = [
	[
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
	],
	[
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
	],
	[
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
	],
	[
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
	],
	[
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
	],
	[
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
	],
	[
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
	],
	[
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
	],
	[
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
		{ value: 0, change: false },
	],
];
